development:
  adapter: postgresql
  encoding: unicode
  database: growing_sprouts_development

test:
  adapter: postgresql
  encoding: unicode
  database: growing_sprouts_test

production:
  adapter: postgresql
  encoding: unicode
  database: growing_sprouts_production